### ISSUE TITLE
Missing Training Data

### ISSUE THREAD

**Issue by Nuelsian** [Simon-Hohberg/Viola-Jones#1]
Hi, Simon, I recently cloned your python translation of the viola jones algorithm, great work. I noticed that the training data to run the algorithm is missing, Is there a way I could get them?

Thanks
Ezenwere Emmanuel, 
emmaezenwere@gmail.com

**Comment by Simon-Hohberg** [comment]
Hi Emmanuel,

thanks, though I am afraid I can't give you the data. My implementation was part of a university project. So I don't have the right to pass on the data. 

Regards,

Simon
