### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by dilpreetdan** [Simon-Hohberg/Viola-Jones#2]
Hello,
Can you please update the readme file to reflect the instructions on how to execute the ViolaJones.py. Specifically, I am unable to understand the directory structure.

I get an error: No module named de.fu.violajones

Thanks!

**Comment by Simon-Hohberg** [comment]
Hi,

thank you for your interest. The project was created quite a while ago, but I am now again working on cleaning it up and adding more documentation on how to use it.

I will report any progress here.

Regards,

Simon

**Comment by syagev** [comment]
Hey, just wanted to add a thumbs-up here. Your repo comes up very high when Google-ing "Viola Jones implementation" and it could be extremely cool to have a nice readme with some instructions, design considerations, etc.

Thanks!

**Comment by Simon-Hohberg** [comment]
Hi,

thanks for your interest. You are of course right, this project strongly needs some documentation. Unfortunately, I am currently very busy.
I started to refactor the code to make it easier to use and I am planning to finish it including documentation next Wednesday (07/12/17).

Regards,

Simon
