### ISSUE TITLE
Problem Training

### ISSUE THREAD

**Issue by ozgurgundogan** [Simon-Hohberg/Viola-Jones#5]
I think there is a problem in testing. I tested different number of classifiers, different size of features and different number of training image. However, it either find all faces correctly (0 correct in non-faces) or find all non-faces correctly (0 correct in faces).
By the way I am using Caltech web faces dataset. Why does it happen ? 

Can you share your dataset which you used in notebook ?

**Comment by Simon-Hohberg** [comment]
Hey,
that sounds strange. The data set that I used came from the university, which is why I am not sure whether I can make it public.
However, I found that the data set [here](https://github.com/INVASIS/Viola-Jones/tree/master/data) is exactly the data set I used.

Regards,

Simon

**Comment by Jim198810** [comment]
Hi Simon,
                   The data set you suggested is of size 19 *19 , it works) ,but  if I want to use a data set of size 64*64, where do I need to change ?

Thanks.
