### ISSUE TITLE
 Image Size of Training Data Set

### ISSUE THREAD

**Issue by Jim198810** [Simon-Hohberg/Viola-Jones#6]
Hi Simon,
The data set you suggested is of size 19 * 19 , (it works) ,but if I want to use images of size 64*64, it does not.
-----------------------------------------------------------------------------
```
Loading faces..
Traceback (most recent call last):
  File "C:\Users\GM\Desktop\Viola-Jones-master\example.py", line 25, in <module>
    faces_ii_training = list(map(ii.to_integral_image, faces_training))
  File "C:\Users\GM\Desktop\Viola-Jones-master\violajones\IntegralImage.py", line 35, in to_integral_image
    integral_image_arr[y+1, x+1] = integral_image_arr[y+1, x-1+1] + row_sum[y, x]
ValueError: setting an array element with a sequence.
```
----------------------------------------------------------------------

where do I need to change ?
Thanks.

**Comment by Simon-Hohberg** [comment]
Hi Jim,
I think this is not an issue with the code. I guess you are using color images, are you? However the code was written for monochrome images, which is why it fails.

Regards,
Simon

**Comment by Jim198810** [comment]
Dear Simon, You are correct, image type was the issue, that has been resolved, but a new issue  arose, that is **MemoryError** . I initially tried to train with 10,000 images of size 200*200 and to test with another 10,000 images of same size but failed to do so, then I decrease the number of training images to 2000, but still I get the bellow error  -

```
Loading faces..
..done. 1000 faces loaded.

Loading non faces..
..done. 1000 non faces loaded.

Creating haar-like features..
..done. 668938 features created.

Calculating scores for images..
Traceback (most recent call last):
  File "C:\Users\GM\Desktop\Viola-Jones-master\example.py", line 31, in <module>
    classifiers = ab.learn(faces_ii_training, non_faces_ii_training, num_classifiers, min_feature_height, max_feature_height, min_feature_width, max_feature_width)
  File "C:\Users\GM\Desktop\Viola-Jones-master\violajones\AdaBoost.py", line 54, in learn
    votes = np.zeros((num_imgs, num_features))
MemoryError
```
How can I solve this issue? this is probably due to my 4 GB RAM.
Also,would you please inform the number of feature values(equivalent to the length of feature vector) generated for each training image (which are also used to test)?


Have you used this implementation in any paper/thesis ? 

Thanks.

**Comment by Jim198810** [comment]
would you please inform the number of feature values(equivalent to the length of feature vector) generated for each training image (which are also used to test)?

**Comment by Simon-Hohberg** [comment]
Hi,

sorry for replying late. I am not sure what you mean with "the number of feature values for each image". What the algorithm does is to generate an exhaustive number of Haar-Like features and then subsequently select the "best" features which can then be used as an ensamble, e.g. cascade.

Regards,

Simon
