### ISSUE TITLE
Sir I'm having trouble running this Please help !!

### ISSUE THREAD

**Issue by shankargadri** [Simon-Hohberg/Viola-Jones#9]
i cloned the code and used it in my virtual environment cv which is configure for opencv version  3.1.0 and python3 . Following error occured can u please explain .

(cv) shank@shankar-pc:~$ python Viola-Jones-master/example.py 
Loading faces..
Traceback (most recent call last):
  File "Viola-Jones-master/example.py", line 19, in <module>
    faces_training = utils.load_images(pos_training_path)
  File "/home/shank/Viola-Jones-master/violajones/Utils.py", line 103, in load_images
    for _file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'trainingdata/faces'

**Comment by Simon-Hohberg** [comment]
Hi,

it seems you don't have any training images under the used path. You should get some training and testing images and then adapt the path accordingly. You can use the dataset [here](https://github.com/INVASIS/Viola-Jones/tree/master/data) for example.

Simon
